package librarysystemfinalinterface;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import java.util.Vector;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//import LibrarySystem.BorrowBook;
//import LibrarySystem.Main;
//import LibrarySystem.PlaceAHold;
//import LibrarySystem.ReturnBookForUser;
//import LibrarySystem.SearchBookForUser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author cec06
 */
public class SearchBookForUser extends javax.swing.JFrame {

	  /**
     * Created by Ashish Gujral
     */
	// creating class object to close the frame-Ashish Gujral
	String Option;
	static SearchBookForUser frame;
	    int q,i;
	    
	    String selectedBook_ID  = null;
	    String selectedBook_Title = null;
	    String selectedBook_Author = null;
	    String selectedBook_Publisher = null;
	    String selectedBook_Edition = null;
	    String selectedBook_Status = null;
	    String selectedBook_ISBN = null;
    public SearchBookForUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        title_user = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_user_login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_user_searchBook = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_borrow_book4 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        
        // Ashish Gujral-- Start
        // for logout button
        btn_user_login.addMouseListener(new MouseAdapter()  
        {  
            public void mouseClicked(MouseEvent e)  
            {  
            	Main.main(new String[] {});
            	frame.dispose();
            }  
        }); 
        // use mouse listener for clicked and open new activity 
        btn_user_searchBook.addMouseListener(new MouseAdapter()  
        {  
            public void mouseClicked(MouseEvent e)  
            {  
            	SearchBookForUser.main(new String[] {});
            	frame.dispose();
            }  
        }); 
        // is for return book
        btn_borrow_book4.addMouseListener(new MouseAdapter()  
        {  
            public void mouseClicked(MouseEvent e)  
            {  
            	ReturnBookForUser.main(new String[] {});
            	frame.dispose();
            }  
        }); 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Search Book");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book Title", "ISBN", "Author", "Due date", "Book Status" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTable3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Author", "Publisher", "Edition", "Status", "ISBN"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
               jTable3MouseClicked(evt);
            }
        });
        
        jScrollPane3.setViewportView(jTable3);

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton9.setText("Borrow");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton10.setText("Display all books");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton12.setText("Reset");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton7))
                        .addComponent(jLabel6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(260, Short.MAX_VALUE)
                    .addComponent(jButton8)
                    .addGap(167, 167, 167)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton9)
                    .addComponent(jButton12))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(389, 389, 389)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 500, 290));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_user.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystemfinalinterface/Icons/icons8-user-32.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(128, 128));
        jLabel1.setPreferredSize(new java.awt.Dimension(128, 128));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("User");

        javax.swing.GroupLayout title_userLayout = new javax.swing.GroupLayout(title_user);
        title_user.setLayout(title_userLayout);
        title_userLayout.setHorizontalGroup(
            title_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        title_userLayout.setVerticalGroup(
            title_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title_userLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel1.add(title_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 40));

        btn_user_login.setBackground(new java.awt.Color(255, 255, 255));
        btn_user_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_user_loginMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystemfinalinterface/Icons/icons8-login-32.png"))); // NOI18N
        jLabel2.setMinimumSize(new java.awt.Dimension(128, 128));
        jLabel2.setPreferredSize(new java.awt.Dimension(128, 128));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Logout");

        javax.swing.GroupLayout btn_user_loginLayout = new javax.swing.GroupLayout(btn_user_login);
        btn_user_login.setLayout(btn_user_loginLayout);
        btn_user_loginLayout.setHorizontalGroup(
            btn_user_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_user_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        btn_user_loginLayout.setVerticalGroup(
            btn_user_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(btn_user_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(btn_user_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 260, 40));

        btn_user_searchBook.setBackground(new java.awt.Color(255, 255, 255));
        btn_user_searchBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_user_searchBookMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystemfinalinterface/Icons/icons8-search-32.png"))); // NOI18N
        jLabel3.setMinimumSize(new java.awt.Dimension(128, 128));
        jLabel3.setPreferredSize(new java.awt.Dimension(128, 128));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Search Book");

        javax.swing.GroupLayout btn_user_searchBookLayout = new javax.swing.GroupLayout(btn_user_searchBook);
        btn_user_searchBook.setLayout(btn_user_searchBookLayout);
        btn_user_searchBookLayout.setHorizontalGroup(
            btn_user_searchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_user_searchBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        btn_user_searchBookLayout.setVerticalGroup(
            btn_user_searchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(btn_user_searchBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(btn_user_searchBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 260, 40));

        btn_borrow_book4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel38.setBackground(new java.awt.Color(204, 204, 204));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysystemfinalinterface/Icons/icons8-return-book-32.png"))); // NOI18N
        jLabel38.setMinimumSize(new java.awt.Dimension(128, 128));
        jLabel38.setPreferredSize(new java.awt.Dimension(128, 128));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setText("Return Book ");

        javax.swing.GroupLayout btn_borrow_book4Layout = new javax.swing.GroupLayout(btn_borrow_book4);
        btn_borrow_book4.setLayout(btn_borrow_book4Layout);
        btn_borrow_book4Layout.setHorizontalGroup(
            btn_borrow_book4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_borrow_book4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel39)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        btn_borrow_book4Layout.setVerticalGroup(
            btn_borrow_book4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(btn_borrow_book4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(btn_borrow_book4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 260, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDisplayAllActionPerformed
        try {
            //Declare the jdbc driver.
        	Connection con=DB.getConnection();
            //Declare the connection to the database.
            //Set the prepared SQL statement.
            PreparedStatement ps=con.prepareStatement
 					("SELECT * FROM BOOK");
            //Excute the SQL statement and get the result set.
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            //Get the amount of column of result set. 
            q = stData.getColumnCount();
            
            //Declare the record table.
            DefaultTableModel RecordTable = (DefaultTableModel)jTable3.getModel();
            RecordTable.setRowCount(0);
            
            //Read the data from result set untill the end.
            while(rs.next()) {
                //Declare a 
                Vector columnData = new Vector();
                
                //Get each values in a row of result set.
                //Then add them to columnData.
                for(i=0;i<q;i++) {
                    columnData.add(rs.getString("BOOK_ID"));
                    columnData.add(rs.getString("BOOK_Title"));
                    columnData.add(rs.getString("BOOK_Author"));
                    columnData.add(rs.getString("BOOK_Publisher"));
                    columnData.add(rs.getString("Book_Edition"));
                    columnData.add(rs.getString("BOOK_Status"));
                    columnData.add(rs.getString("ISBN"));
                }
                //Append each to RecordTable.
                RecordTable.addRow(columnData);
                //Close the connection.
                //con.close();  
            }
        }catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_btnUserDisplayAllActionPerformed
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    	
    	 Option = jComboBox1.getSelectedItem().toString();
    	 if(Option.equals("Book ID")) {
			 Option = "Book_id";
		 }
		 else if(Option.equals("Book Title")) {
			 Option = "Book_title";
		 }
		 else if(Option.equals("Author")) {
			 Option = "Book_author";
		 }
		 else if(Option.equals("Publisher")) {
			 Option = "Book_publisher";
		 }
		 else if(Option.equals("Book_Edition")) {
			 Option = "Book_edition";
		 }
		 else if(Option.equals("Book Status")) {
			 Option = "Book_status";
		 }
		 else if(Option.equals("ISBN")) {
			 Option = "ISBN";
		 }
		 else {
		 Option="Book_title";
		 }
         
         try {
        	 Connection con=DB.getConnection();
             //Declare the connection to the database.
             //Set the prepared SQL statement.
        	 PreparedStatement ps=con.prepareStatement
	 					("select * from book where "+Option+" =? ");
         
          ps.setString(1, jTextField6.getText());
             ResultSet rs = ps.executeQuery();
  		            ResultSetMetaData stData = rs.getMetaData();
             //Declare the connection to the database.
             
  		         
           
             
             //Excute the SQL statement and get the result set.
            
             
             //Get the amount of column of result set. 
             q = stData.getColumnCount();
             
             //Declare the record table.
             DefaultTableModel RecordTable = (DefaultTableModel)jTable3.getModel();
             RecordTable.setRowCount(0);
             
             //Read the data from result set untill the end.
             while(rs.next()) {
                 //Declare a 
                 Vector columnData = new Vector();
                 
                 //Get each values in a row of result set.
                 //Then add them to columnData.
                 for(i=0;i<q;i++) {
                     columnData.add(rs.getString("BOOK_ID"));
                     columnData.add(rs.getString("BOOK_Title"));
                     columnData.add(rs.getString("BOOK_Author"));
                     columnData.add(rs.getString("BOOK_Publisher"));
                     columnData.add(rs.getString("Book_Edition"));
                     columnData.add(rs.getString("BOOK_Status"));
                     columnData.add(rs.getString("ISBN"));
                 }
                 //Append each to RecordTable.
                 RecordTable.addRow(columnData);
                 //Close the connection.
                 //con.close();  
             }
         }catch(Exception ex) {
             JOptionPane.showMessageDialog(null, ex);
         } // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btn_user_loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_user_loginMousePressed
        // TODO add your handling code here:
        //        setColor(btn_user_login);
        //        resetColor(btn_user_searchBook);
    }//GEN-LAST:event_btn_user_loginMousePressed

    private void btn_user_searchBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_user_searchBookMouseClicked
        // TODO add your handling code here:
        //        setColor(btn_user_searchBook);
        //        resetColor(btn_user_login);
    }//GEN-LAST:event_btn_user_searchBookMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed
    
    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)jTable3.getModel();
        int selectedRows =jTable3.getSelectedRow();
        
        selectedBook_ID = RecordTable.getValueAt(selectedRows, 0).toString(); 
        selectedBook_Title = RecordTable.getValueAt(selectedRows, 1).toString(); 
        selectedBook_Author = RecordTable.getValueAt(selectedRows, 2).toString(); 
        selectedBook_Publisher = RecordTable.getValueAt(selectedRows, 3).toString(); 
        selectedBook_Edition = RecordTable.getValueAt(selectedRows, 4).toString(); 
        selectedBook_Status = RecordTable.getValueAt(selectedRows, 5).toString(); 
        selectedBook_ISBN = RecordTable.getValueAt(selectedRows, 6).toString(); 
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    	if(selectedBook_ID == null) {
            JOptionPane.showMessageDialog(this, "Please select at least one book.");
        } else {
            try {Connection con=DB.getConnection();
            //Declare the connection to the database.
            //Set the prepared SQL statement.
            PreparedStatement ps=con.prepareStatement
 					("SELECT * FROM BOOK");
            int userid=0;
            //Set the prepared SQL statement.
            switch(selectedBook_Status) {
                case "1":
                    JOptionPane.showMessageDialog(this, "This book is not available now.");
                    break;
                case "0":
                	ZoneId systemTimeZone = ZoneId.systemDefault();
                     
                     LocalDate startDate = LocalDate.now();                    
                     ZonedDateTime zonedDateTime = startDate.atStartOfDay(systemTimeZone);
                     Date startDay = Date.from(zonedDateTime.toInstant());
                     java.sql.Date sqlStartDate = new java.sql.Date(startDay.getTime());
                 
                     LocalDate dueDate = startDate.plusDays(14);
                     ZonedDateTime zonedDateTime2 = dueDate.atStartOfDay(systemTimeZone);
                     Date dueDay = Date.from(zonedDateTime2.toInstant());
                     java.sql.Date sqlDueDate = new java.sql.Date(dueDay.getTime());
                     //String formattedDueDate = dueDate.format(DateTimeFormatter.ofPattern("dd-MMM-yy"));
          
                     ps = con.prepareStatement("UPDATE book SET Book_Status=1 WHERE Book_ID=?");
                     ps.setString(1, selectedBook_ID);
                     //Excute the SQL statement and get the result set.
                     ps.executeUpdate();
                     ps= con.prepareStatement("Select User_ID from user where User_Eamil=?");
                     ps.setString(1,UserLogin.globalName);
                     ResultSet rs=ps.executeQuery();
         			 if(rs.next()) {
         				userid=rs.getInt("User_ID");
         			 }
                     ps = con.prepareStatement("INSERT INTO borrow_detail (Start_Date, Due_Date,User_User_ID, Book_Book_ID) "
                             + "VALUES(?, ?, ?, ?)");
                     ps.setDate(1, sqlStartDate);
                     ps.setDate(2, sqlDueDate);
                     ps.setInt(3, userid);
                     ps.setString(4,selectedBook_ID);
                     //Excute the SQL statement and get the result set.
                     ps.executeUpdate();
                     
                     JOptionPane.showMessageDialog(this, "Borrowed!");
                    
                    break;
                default:
                    break;
            }
        }catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed


    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
    	 jTextField6.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBookForUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBookForUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBookForUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBookForUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	try {
   					frame =  new SearchBookForUser();
   					frame.setVisible(true);
   					} 
                  catch (Exception e) {
   					e.printStackTrace();
   				}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_borrow_book4;
    private javax.swing.JPanel btn_user_login;
    private javax.swing.JPanel btn_user_searchBook;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel title_user;
    // End of variables declaration//GEN-END:variables
}
